[project]
name = "interviewscreener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.8",
    "langgraph>=1.0.3",
    "sqlalchemy",
    "sqlmodel>=0.0.27",
]
